### ISSUE TITLE
Python 3 Support Not Implemented

### ISSUE THREAD

**Issue by mfrager** [machinalis/quepy#45]
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    import quepy
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/quepy/__init__.py", line 17, in <module>
    from quepy.quepyapp import install, QuepyApp
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/quepy/quepyapp.py", line 41
    except ImportError, error:
                      ^
SyntaxError: invalid syntax

**Comment by rafacarrascosa** [comment]
Thanks, would you submit a PR?

**Comment by prasad83** [comment]
except syntax changed in python3 should be

except (ImportError) as error:
